### ISSUE TITLE
Node 20 dependency is a breaking change that was release as a patch version

### ISSUE THREAD

**Issue by cliffchapmanrbx** [NuGet/setup-nuget#119]
Hi team,

We run GitHub Enterprise Server, which follows an extended version release cycle and support cycle that is longer than GitHub Cloud. Our GitHub Actions runners currently don't support Node 20. We're slowly working through the dependency tree to get there, but will take some more time.

Changing the GHA runner installed dependencies is a backwards-incompatible change, but was released as a patch version for #112. This caused a fair number of our workflows to break.

Could you please revert the change for v1 and release a v2 that contains the Node 20 update? We've seen several other Actions repos that follow this pattern.

**Comment by jeffkl** [comment]
Done, v2, v2.0, and v2.0.0 now point to the latest release and v1 points to v1.2.0 which is the latest before the Node 20 change
