### ISSUE TITLE
Deprecated 'set-env' command errors

### ISSUE THREAD

**Issue by champeauxr** [NuGet/setup-nuget#21]
I'm getting errors saying the 'set-env' command is deprecated and will be disabled on November 16th, 2020.

![image](https://user-images.githubusercontent.com/8657174/98942379-e4bce100-24bb-11eb-95cc-17459225dae4.png)

**Comment by dbeuchler** [comment]
This is already fixed in #11 - use `@v1.0.5` within your workflow file.

**Comment by zkat** [comment]
Hm. Did I not sync v1 with 1.0.5? I'll check once I'm at my desk

**Comment by zkat** [comment]
@champeauxr can you post the more detailed log? `v1` should definitely be `v1.0.5`, which fixes this error.

**Comment by champeauxr** [comment]
It does indeed seem to be working fine now. I no longer have the logs for that specific run, since I re-ran that job several times while debugging one of my own actions, and the most recent run doesn't have this error. 

The only log I have showing this error (which no longer occurs) is from 11/6/2020.

**Comment by zkat** [comment]
Great! This is resolved, then. 👍🏻
