### ISSUE TITLE
Create a v1 branch

### ISSUE THREAD

**Issue by jethas-bennettjones** [NuGet/setup-nuget#23]
Hi,

I was wondering if it would be possible to create a v1 branch for this project. The recent introduction of .NET 5, and the required changes around it, have broken all of our build scripts for projects that use .NET 5. I have seen with other projects that minor changes such as these are deployed to a v1 branch, and the scripts that use these actions just pull the latest version and use that.
I don't see this is a breaking change, especially since you incremented the patch value for the release.

Do you think this would be possible?

**Comment by jeffkl** [comment]
We've created a `v1` tag that can be used to always have the latest v1 version.  There are also `major.minor.patch` tags that you can use to specify a specific version just in case there's an unintentional breaking change.

https://github.com/NuGet/setup-nuget/tags
