### ISSUE TITLE
'latest' version usage

### ISSUE THREAD

**Issue by a-a-k** [NuGet/setup-nuget#52]
I was not able to apply the version tag using `uses: NuGet/setup-nuget@latest` syntax.    

> Unable to resolve action `NuGet/setup-nuget@latest`, unable to find version `latest`

Which syntax should I use, since the README lacks this info?

**Comment by jeffkl** [comment]
> I was not able to apply the version tag using uses: NuGet/setup-nuget@latest syntax.

The available tags are here: https://github.com/NuGet/setup-nuget/tags

Basically there's a tag for each major, minor, and patch version.  You can use `v1` for the latest version 1, `v1.1` for the latest version 1.1, and you can be very specific and specify `v1.2.0`

This only specifies the version of the GitHub task.  If you want latest, at the moment `v1` is what will work best.  If we ship a new version that has a breaking change, we'd ship it as `v2` to avoid breaking people and they need to update to `v2` at their convenience and address any issues.

The `latest` specifies which version of `NuGet.exe` to use.

**Comment by a-a-k** [comment]
> The latest specifies which version of NuGet.exe to use.

okay, seems I misunderstood this point. thanks
